### ISSUE TITLE
Run-time error of testEKF_completeLegWithSkin.m

### ISSUE THREAD

**Issue by prashanthr05** [jeljaik/extended-kalman-filter#23]
I installed the EKF library and tried to run the script testEKF_completeLegWithSkin.m under the EKF_EulerAngles folder of dynamic-tests branch. I can see the plots being plotted but it suspends showing the following error,

"Attempt to reference field of non-structure array.

Error in plotResultsOutput_withSkin (line 19)
figPreN = figPreN.Number - 1;

Error in plotAndSaveFigs (line 2)
    plotResultsOutput_withSkin(dataBaseFolder);

Error in testEKF_completeLegWithSkin (line 227)
plotAndSaveFigs(dataBaseFolder,plotFigBaseFolder);"

**Comment by nunoguedelha** [comment]
Actually, it's just the access to `figPreN.Number` which is failing because `figPreN` is not a structure but a number. It's the reference number of the figure created in the previous line. `figure(N)` can be used to create a new figure of reference N or access figure N if it already exists. Just remove `.Number` and it works.

**Comment by jeljaik** [comment]
Yeah, but this also varies from one Matlab version to other. At some point
they added/removed this Number method

**Comment by naveenoid** [comment]
Will try implementing a version check for this. Ultimately I prefer the plots generated from Jorh's version, which I guess is 2014? So we must retain compatibility with him.

**Comment by jeljaik** [comment]
Well said

## 

_Jorhabib Eljaik Gómez,_*Ph.D. Student - *Istituto Italiano di Tecnologia
Dept. of Robotics, Brain and Cognitive Sciences
Cognitive Humanoids Laboratory
e-mail: jorhabib.eljaik@iit.it
Cel: +39 388 352 33 85
Tel: +39 010 71781 420
Fax: +39 010 7170817

On Thu, Apr 30, 2015 at 2:24 PM, Naveen Kuppuswamy <notifications@github.com
