### ISSUE TITLE
Interfacing with XSens

### ISSUE THREAD

**Issue by jeljaik** [jeljaik/extended-kalman-filter#26]
MT Software Suite can be obtained from https://www.xsens.com/mt-software-suite/
- If the IMU is recognized via USB, you should read this after `lsusb`
  `Bus 002 Device 006: ID 0403:d38b Future Technology Devices International, Ltd`
- In the directory `MT_Software_Suite_Linux_4.3` you want to run `mtsdk_linux_4.3.sh` which is the MT SDK.
- If you run into this error message

``` bash
'realpath' could not be found. It is usually installed with the 'realpath' package
'uudecode' could not be found. It is usually installed with the 'sharutils' package
```

Simply do: 

``` bash
sudo apt-get install realpath && sudo apt-get install sharutils
```
- If you want to install in the default directory `/usr/local` just hit `Enter` when it asks to Enter the installation directory. Afterwards you will find in this directory all the libraries, headers and examples necessary for you to start collecting data straight from the sensor.
- The first example you wanna try is in `/usr/local/xsens/examples/mtsdk/src_cpp`. To compile do: `make src_cpp`. Enter src_cpp `cd src_cpp` and run `./example`
- If it recognizes the device but it can't access the device do the following as found in `README.MTSDK`

``` bash
The device is recognized, but I cannot ever access the device -

    Make sure you are in the correct group (often dialout or uucp) in order to
    access the device. You can test this with

        $ ls -l /dev/ttyUSB0
        crw-rw---- 1 root dialout 188, 0 May  6 16:21 /dev/ttyUSB0
        $ groups
        dialout audio video usb users plugdev

    If you aren't in the correct group, you can fix this in two ways.

    1. Add yourself to the correct group
        You can add yourself to it by using your distributions user management
        tool, or call

            $ sudo usermod -G dialout -a $USER

        Be sure to replace dialout with the actual group name if it is
        different. After adding yourself to the group, either relogin to your
        user, or call

            $ newgrp dialout

        to add the current terminal session to the group.
```

**It is strongly recommended to log out and back in after these changes for them to take effect** 
- The output of the example module will look like this: 
  `W:-0.72,X: 0.22,Y:-93.12,Z: 0.00,Roll: -82.13,Pitch:  90.00,Yaw: -89.80^C0.00,Yaw: -90.000w:  90.00: -90.000`

**Comment by jeljaik** [comment]
@naveenoid Can you give me a hand to document this? How to install the XSens driver on Linux and pointers to good documentation and info. I'm getting started myself on this.

**Comment by naveenoid** [comment]
in.. will checkout your progress and start adding my own comments

---

Naveen Kuppuswamy, PhD
Post-doctoral Fellow,
Cognitive Humanoids Lab,
Department of Robotics, Brain and Cognitive Sciences (RBCS),
Istituto Italiano di Tecnologia, Genova, Italy
